[package]
name = "ratboy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_app = "0.16.1"
bevy_asset = "0.16.1"
bevy_input = "0.16.1"
bevy_rapier2d = "0.30.0"
bevy_render = "0.16.1"
